spring:
  application:
    name: schedule-service
  # 连接mysql
  datasource:
    url: jdbc:mysql://localhost:3306/chongba
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: liuche
  redis:
    host: 192.168.253.3
    password: liuche
    database: 1
    port: 6379
chongba:
  preLoad: 2 #预加载时间配置