server:
  port: 9100
spring:
  application:
    name: schedule-service
  # 连接mysql
  datasource:
    url: jdbc:mysql://localhost:3306/chongba
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: liuche
  redis:
    host: 192.168.253.3
    password: liuche
    database: 1
    port: 6379
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
chongba:
  preLoad: 1 #预加载时间配置
  selectMasterZookeeper: 192.168.253.3:2181
  name: liuche