server:
  port: 99
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: supplier
  # 连接mysql
  datasource:
    url: jdbc:mysql://localhost:3306/chongba
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: liuche
  redis:
    host: 192.168.253.3
    password: liuche
    database: 1
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
rocketmq:
  name-server: 192.168.253.3:9876
  producer:
    group: chongba-group
supplier:
  apis: {
    "jisuapi": "http://127.0.0.1:8090/jisuapi/mobilerecharge/recharge",
    "juheapi": "http://127.0.0.1:8090/juheapi/recharge"
        }
  maxrepeat: 4 # 最大重试次数